# Generated by Django 4.2 on 2023-05-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(choices=[('Cola', 'Coca Cola'), ('Fanta', 'Fanta'), ('Sprite', 'Sprite'), ('Fuse', 'Fuse tea'), ('Maxi', 'Maxi tea')], default='Coca Cola', max_length=10)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinks.amount')),
            ],
        ),
    ]
