# Generated by Django 4.2 on 2023-05-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='num',
            new_name='amount',
        ),
    ]
