# Generated by Django 4.2 on 2023-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_rename_num_amount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
