# Generated by Django 4.2 on 2023-05-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_alter_drink_amount_delete_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_name',
            field=models.CharField(choices=[('Cola', 'Coca Cola'), ('Fanta', 'Fanta'), ('Sprite', 'Sprite'), ('Fuse', 'Fuse tea'), ('Maxi', 'Maxi tea'), ('Piko', 'Piko')], default='Coca Cola', max_length=10),
        ),
    ]
